---
sidebar: sidebar 
permalink: scpivs44_restore_from_backups_overview.html 
keywords:  
summary: Es posible restaurar máquinas virtuales, VMDK, archivos y carpetas desde backups primarios o secundarios. 
---
= Descripción general
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible restaurar máquinas virtuales, VMDK, archivos y carpetas desde backups primarios o secundarios.

* Destinos de restauración de máquinas virtuales
+
En el plugin de SnapCenter para VMware vSphere 4.4 y versiones anteriores, puede restaurar máquinas virtuales solo en el host y el almacén de datos originales.

+
A partir del plugin de SnapCenter para VMware vSphere 4.5, puede restaurar máquinas virtuales en el host original, o en un host alternativo en la misma instancia de vCenter Server, o en un host ESXi alternativo gestionado por la misma instancia de vCenter o cualquier instancia de vCenter en modo vinculado.

* Destinos de restauración VMDK
+
Puede restaurar los VMDK tanto para el almacén de datos original como para otro alternativo.



También es posible restaurar archivos y carpetas individuales en una sesión de restauración de archivos de invitado, que conecta una copia de backup de un disco virtual y luego restaura los archivos y las carpetas que se seleccionan.

No puede restaurar lo siguiente:

* Almacenes de datos
+
No es posible usar el plugin de SnapCenter para VMware vSphere para restaurar un almacén de datos, ya que solo se aplica a las máquinas virtuales individuales del almacén de datos.

* Backups de máquinas virtuales eliminadas
+
No es posible restaurar backups de máquinas virtuales de almacenamiento que se quitaron. Por ejemplo, si agrega una máquina virtual de almacenamiento mediante la LIF de gestión y, a continuación, crea un backup y luego elimina esa máquina virtual de almacenamiento y añade un clúster que contiene esa misma máquina virtual de almacenamiento, se producirá un error en la operación de restauración para el backup.


